tasks:
  - name: Scratch Space
  - name: Dev Server
    init: npm install && npm run build
    command: npm run dev
    openMode: split-right
  - name: Local Database
    command: docker-compose up
    openMode: split-right